In [5]:
import numpy as np

In [56]:
M = np.array([[1,3,1,2], [1,2,5,8], [3,1,2,9], [5,4,2,1]])
M

array([[1, 3, 1, 2],
       [1, 2, 5, 8],
       [3, 1, 2, 9],
       [5, 4, 2, 1]])

In [58]:
S = M[1:3, 0:3]
S

array([[1, 2, 5],
       [3, 1, 2]])

In [59]:
N = np.array([[2,3,1], [5,1,3]])
N

array([[2, 3, 1],
       [5, 1, 3]])

In [60]:
P = N.T
P

array([[2, 5],
       [3, 1],
       [1, 3]])

In [72]:
X = S.dot(P)
X

array([[13, 22],
       [11, 22]])